// Handles clicks on browser push notifications generated by dashboard.js.
self.addEventListener('notificationclick', event => {
  event.notification.close();

  event.waitUntil((async () => {
    // Reuse an already-open dashboard tab when possible; otherwise open one.
    const windows = await clients.matchAll({ type: 'window', includeUncontrolled: true });
    const openWindow = windows.find(client => client.url.includes(self.location.origin));

    if (openWindow) {
      await openWindow.focus();
      return;
    }

    await clients.openWindow('/');
  })());
});
